### ISSUE TITLE
Add vedio player Functionality

### ISSUE THREAD

**Issue by PIYUSH-69** [CSI-DMCE-2024/Image_Drive-Hacktoberfest2024#3]
Add a vedio player functionality in the 3 rd tab where vedios can be fetched from firebase and played in the recylerview

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?

**Comment by PIYUSH-69** [comment]
@DeadInsane5 Yes you can start working on this enhancement task. Try to compelete the task within 24 hours

**Comment by DeadInsane5** [comment]
> @DeadInsane5 Yes you can start working on this enhancement task. Try to compelete the task within 24 hours

Thanks for assigning me
Would really appreciate if I could possibly get 48 hours to implement the feature

**Comment by DeadInsane5** [comment]
> @DeadInsane5 Yes you can start working on this enhancement task. Try to compelete the task within 24 hours

Issue is fixed by me and I've created a PR, kindly request you to review the PR
Thanks in advance

**Comment by PIYUSH-69** [comment]
@DeadInsane5 Yes, Thank you for contributing. Can you send a short recording of the application showing the 3rd tab ?

**Comment by DeadInsane5** [comment]
> @DeadInsane5 Yes, Thank you for contributing. Can you send a short recording of the application showing the 3rd tab ?

I can't, I've added 'Video player functionality' however, the 'upload video' is a different issue already open 
I can't test or show recordings of Video player unless Videos are uploaded to firebase

Let me know if I've misunderstood the task
